name = "vrsprototype"
type = "javascript"
main = "../workers-site/index.js"
account_id = "1ff4c07cf2d9257ced232d5cf6abba1a"
compatibility_date = "2024-07-14"

[build]

command = "npm run build"
cwd = "/var/www/html/nvrs-frontend/" # Run the build command in the nvrs-frontend directory

[site]
bucket = "/var/www/html/workers-site" 
# entry-point = "workers-site" # Optional if you're not using a custom build

[env.production]
workers_dev = true
route = "vrsprototype.com/*"
zone_id = "fb062b8145b27c01ebef70d117512f4c"
