name = "vrsprototype"
main = "workers-site/index.js"
account_id = "1ff4c07cf2d9257ced232d5cf6abba1a"
compatibility_date = "2024-07-14"

[site]
bucket = "./out"
#entry-point = "."

[env.production]
workers_dev = false
route = "vrsprototype.com"
zone_id = "fb062b8145b27c01ebef70d117512f4c"
